name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image
        run: docker build -t gmullblack2/dev-env:latest .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image for vulnerabilities
        id: trivy-scan
        run: trivy image --format json -o trivy-report.json gmullblack2/dev-env:latest

      - name: Push Docker image to registry
        run: docker push gmullblack2/dev-env:latest

      - name: Send email with scan report
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          curl -s --user "api:${MAILGUN_API_KEY}" \
          https://api.mailgun.net/v3/${MAILGUN_DOMAIN}/messages \
          -F from='sender@example.com' \
          -F to=${EMAIL_TO} \
          -F subject='Docker Image Scan Report' \
          -F text='Please find the attached scan report for the Docker image.' \
          -F attachment=@trivy-report.json
